
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5454/postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
      show_sql: true
server:
  port: 8090